import 'dart:math';
import 'dart:typed_data';

import 'cancellation.dart';
import 'chat_history.dart';
import 'safe_metadata.dart';

/// A bounded clip captured by an explicit push-to-talk action.
final class SpeechAudio {
  SpeechAudio({required this.bytes, required String mimeType})
    : mimeType = normalizeAudioMimeType(mimeType);

  final Uint8List bytes;
  final String mimeType;
}

final class SpeechTranscript {
  const SpeechTranscript({required this.text, required this.engine});

  final String text;

  /// Display-safe description of the engine and where it ran.
  final String engine;
}

final class SynthesizedSpeech {
  const SynthesizedSpeech({
    required this.bytes,
    required this.mimeType,
    required this.engine,
    this.truncated = false,
  });

  final Uint8List bytes;
  final String mimeType;
  final String engine;

  /// Whether only the beginning of the reply was spoken.
  final bool truncated;
}

abstract interface class SpeechTranscriber {
  String get engine;

  Set<String> get supportedMimeTypes;

  Future<SpeechTranscript> transcribe(
    SpeechAudio audio, {
    CancellationToken? cancellationToken,
  });
}

abstract interface class SpeechSynthesizer {
  String get engine;

  Future<SynthesizedSpeech> synthesize(
    String text, {
    CancellationToken? cancellationToken,
  });
}

/// A user-facing voice failure; the message is safe to show to clients.
final class SpeechException implements Exception {
  const SpeechException(this.message);

  final String message;

  @override
  String toString() => message;
}

/// Converts push-to-talk audio into transcripts and assistant replies into
/// speech. Audio is never stored; only transcripts enter history.
final class VoiceService {
  VoiceService({
    required ChatHistoryStore store,
    this.transcriber,
    this.synthesizer,
    this.maxAudioBytes = defaultMaxAudioBytes,
    this.maxSpokenCharacters = defaultMaxSpokenCharacters,
  }) : _store = store {
    if (maxAudioBytes < 1) {
      throw ArgumentError.value(
        maxAudioBytes,
        'maxAudioBytes',
        'must be positive',
      );
    }
    if (maxSpokenCharacters < 80) {
      throw ArgumentError.value(
        maxSpokenCharacters,
        'maxSpokenCharacters',
        'must be at least 80',
      );
    }
  }

  /// About one minute of 16 kHz, 16-bit mono WAV.
  static const defaultMaxAudioBytes = 2 * 1024 * 1024;
  static const defaultMaxSpokenCharacters = 800;

  /// RMS below roughly -54 dBFS is treated as silence.
  static const silenceThreshold = 0.002;

  final ChatHistoryStore _store;
  final SpeechTranscriber? transcriber;
  final SpeechSynthesizer? synthesizer;
  final int maxAudioBytes;
  final int maxSpokenCharacters;

  bool get inputAvailable => transcriber != null;
  bool get outputAvailable => synthesizer != null;

  /// Explains where audio goes; null when voice is not configured.
  String? get privacyNotice {
    final input = transcriber;
    final output = synthesizer;
    if (input == null && output == null) return null;
    return [
      if (input != null)
        'Push-to-talk audio is transcribed by ${input.engine} and deleted '
            'after transcription. The transcript joins this conversation.',
      if (output != null)
        'Spoken replies are generated by ${output.engine} and are not stored.',
    ].join(' ');
  }

  /// Validates [audio] and returns a non-empty transcript.
  Future<SpeechTranscript> transcribe(
    SpeechAudio audio, {
    CancellationToken? cancellationToken,
  }) async {
    final transcriber =
        this.transcriber ??
        (throw const SpeechException(
          'Voice input is not configured on this host.',
        ));
    if (audio.bytes.isEmpty) {
      throw const SpeechException('The recording is empty.');
    }
    if (audio.bytes.length > maxAudioBytes) {
      throw const SpeechException(
        'The recording is too long. Keep voice messages under a minute.',
      );
    }
    if (!transcriber.supportedMimeTypes.contains(audio.mimeType)) {
      throw SpeechException(
        'Unsupported audio type ${SafeMetadata.text(audio.mimeType).text}. '
        'Use ${transcriber.supportedMimeTypes.join(', ')}.',
      );
    }
    if (!_hasExpectedHeader(audio)) {
      throw SpeechException('The recording is not valid ${audio.mimeType}.');
    }
    final level = wavRmsLevel(audio.bytes);
    if (level != null && level < silenceThreshold) {
      throw const SpeechException('No speech was detected in the recording.');
    }
    final result = await transcriber.transcribe(
      audio,
      cancellationToken: cancellationToken,
    );
    final text = normalizeTranscript(result.text);
    if (text.isEmpty) {
      throw const SpeechException('No speech was recognized.');
    }
    return SpeechTranscript(
      text: text,
      engine: SafeMetadata.text(result.engine).text,
    );
  }

  /// Synthesizes the assistant reply identified by [entryId].
  Future<SynthesizedSpeech> speak({
    required String conversationId,
    required String entryId,
    CancellationToken? cancellationToken,
  }) async {
    final synthesizer =
        this.synthesizer ??
        (throw const SpeechException(
          'Spoken replies are not configured on this host.',
        ));
    final entry = (await _store.history(
      conversationId,
    )).where((entry) => entry.entryId == entryId).firstOrNull;
    if (entry == null || entry.kind != ChatEntryKind.assistantMessage) {
      throw const SpeechException('Only assistant replies can be spoken.');
    }
    final spoken = spokenText(
      entry.content,
      maxCharacters: maxSpokenCharacters,
    );
    if (spoken.text.isEmpty) {
      throw const SpeechException('The reply has no speakable text.');
    }
    final speech = await synthesizer.synthesize(
      spoken.text,
      cancellationToken: cancellationToken,
    );
    if (speech.bytes.isEmpty) {
      throw const SpeechException('The speech engine returned no audio.');
    }
    return SynthesizedSpeech(
      bytes: speech.bytes,
      mimeType: speech.mimeType,
      engine: SafeMetadata.text(speech.engine).text,
      truncated: spoken.truncated || speech.truncated,
    );
  }

  bool _hasExpectedHeader(SpeechAudio audio) {
    final bytes = audio.bytes;
    bool starts(String marker, [int offset = 0]) =>
        bytes.length >= offset + marker.length &&
        String.fromCharCodes(bytes, offset, offset + marker.length) == marker;
    return switch (audio.mimeType) {
      'audio/wav' => starts('RIFF') && starts('WAVE', 8),
      'audio/flac' => starts('fLaC'),
      'audio/mpeg' =>
        starts('ID3') ||
            (bytes.length > 1 && bytes[0] == 0xff && bytes[1] & 0xe0 == 0xe0),
      _ => true,
    };
  }
}

/// Maps common aliases to one canonical MIME type and drops parameters.
String normalizeAudioMimeType(String value) {
  final base = value.split(';').first.trim().toLowerCase();
  return switch (base) {
    'audio/x-wav' || 'audio/wave' || 'audio/vnd.wave' => 'audio/wav',
    'audio/mp3' => 'audio/mpeg',
    'audio/x-flac' => 'audio/flac',
    _ => base,
  };
}

/// Removes non-speech annotations such as `[BLANK_AUDIO]` or `(music)`.
String normalizeTranscript(String value) {
  final speech = value
      .replaceAll(RegExp(r'\[[^\]]*\]'), ' ')
      .replaceAll(RegExp(r'\([^)]*\)'), ' ')
      .trim();
  return speech.isEmpty
      ? ''
      : SafeMetadata.text(speech, maxCharacters: 32000).text;
}

/// Converts Markdown into bounded prose suitable for reading aloud.
SafeSummary spokenText(String markdown, {required int maxCharacters}) {
  final text = markdown
      .replaceAll(
        RegExp(r'```[\s\S]*?(?:```|$)'),
        ' Code is shown in the conversation. ',
      )
      .replaceAllMapped(
        RegExp(r'!?\[([^\]]*)\]\([^)]*\)'),
        (match) => match[1] ?? '',
      )
      .replaceAllMapped(RegExp(r'`([^`]*)`'), (match) => match[1] ?? '')
      .replaceAll(
        RegExp(r'^\s{0,3}(?:#{1,6}|>|[-*+]|\d+[.)])\s+', multiLine: true),
        '',
      )
      .replaceAll(RegExp(r'\*\*|__|~~|\*'), '')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();
  if (text.length <= maxCharacters) return SafeSummary(text);
  var cut = text.substring(0, maxCharacters);
  final sentenceEnd = cut.lastIndexOf(RegExp(r'[.!?](?=\s)'));
  if (sentenceEnd > maxCharacters ~/ 2) {
    cut = cut.substring(0, sentenceEnd + 1);
  } else {
    final space = cut.lastIndexOf(' ');
    if (space > 0) cut = cut.substring(0, space);
  }
  return SafeSummary(
    '${cut.trim()} The full reply is in the conversation.',
    truncated: true,
  );
}

/// Root-mean-square level of 16-bit PCM WAV audio from 0 to 1, or null when
/// the clip is not 16-bit PCM WAV.
double? wavRmsLevel(Uint8List bytes) {
  String id(int offset) => String.fromCharCodes(bytes, offset, offset + 4);
  if (bytes.length < 12 || id(0) != 'RIFF' || id(8) != 'WAVE') return null;
  final data = ByteData.sublistView(bytes);
  int? format;
  int? bitsPerSample;
  int? dataOffset;
  int? dataLength;
  var offset = 12;
  while (offset + 8 <= bytes.length) {
    final size = data.getUint32(offset + 4, Endian.little);
    final body = offset + 8;
    final remaining = bytes.length - body;
    if (id(offset) == 'fmt ' && size >= 16 && remaining >= 16) {
      format = data.getUint16(body, Endian.little);
      bitsPerSample = data.getUint16(body + 14, Endian.little);
    } else if (id(offset) == 'data') {
      dataOffset = body;
      dataLength = size == 0 || size > remaining ? remaining : size;
      break;
    }
    offset = body + size + size % 2;
  }
  if (format != 1 || bitsPerSample != 16 || dataOffset == null) return null;
  final samples = dataLength! ~/ 2;
  if (samples == 0) return 0;
  var sumOfSquares = 0.0;
  for (var index = 0; index < samples; index++) {
    final sample = data.getInt16(dataOffset + index * 2, Endian.little);
    sumOfSquares += sample * sample;
  }
  return sqrt(sumOfSquares / samples) / 32768;
}
