apiServer:
  port: 0
  publicHost: localhost
  publicPort: 0
  publicScheme: http
database:
  filePath: storage.db
sessionLogs:
  persistentEnabled: false
  consoleEnabled: true
  consoleLogFormat: json
