name: dextero_app
description: Flutter client for the local Dextero server.
publish_to: none
version: 0.0.1+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: 3.47.2

resolution: workspace

dependencies:
  dextero_server:
    path: ../server
  flutter:
    sdk: flutter
  shad: ^0.99.4
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
